create table "customer" (
  "id" bigint generated by default as identity (start with 1) not null primary key,
  "name" varchar(255) not null
  "age" int not null
);
insert into "customer" ("name","age")  values ("Juan",22);

drop table "customer" if exists;
